apiVersion: core.k8sgpt.ai/v1alpha1
kind: K8sGPT
metadata:
  name: k8sgpt-sample
  namespace: k8sgpt-operator-system
spec:
  ai:
    enabled: true
    model: gpt-4o-mini
    backend: openai
    secret:
      name: openai-secret
      key: api-key
  # Explicitly define the repository and version to fix the InvalidImageName error
  repository: ghcr.io/k8sgpt-ai/k8sgpt
  version: v0.3.41
  noCache: true